version: "3"
services:
  mongo:
    build: .
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    extra_hosts:
      - "host1:172.31.1.213"
      - "host2:172.31.27.95"
      - "host3:172.31.19.204"
      - "rs0.cocoice.icu:172.31.1.213"
      - "rs1.cocoice.icu:172.31.27.95"
      - "rs2.cocoice.icu:172.31.19.204"
    command: mongod --tlsMode requireTLS --tlsCertificateKeyFile /etc/ssl/mongodb.pem
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    logging:
      driver: "json-file"
      options:
          max-size: "10m"
          max-file: "5"
    
volumes: 
  mongodata:

