version: "3"
services:
  mongo:
    build: .
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    command: mongod --replSet rs1 
    extra_hosts:
      - "host1:54.180.115.98"

volumes: 
  mongodata:
