version: "3"
services:
  mongo:
    build: .
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
      - mongolog:/var/log/mongodb
    extra_hosts:
      - "host1:172.31.1.213"
      - "host2:172.31.27.95"
      - "host3:172.31.19.204"
    command: mongod --replSet rs1 --keyFile ./init/replica.key
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    
volumes: 
  mongodata:
  mongolog:

