version: "3"
services:
  mongo:
    build: .
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    extra_hosts:
      - "host1:172.31.3.103"
      - "host2:172.31.27.95"
      - "host3:172.31.19.204"

volumes: 
  mongodata:
